-- Run this in Supabase SQL editor to create the tables and sample teacher account.

CREATE TABLE IF NOT EXISTS teachers (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    subject VARCHAR(100) NOT NULL,
    room VARCHAR(50),
    email VARCHAR(150) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS slots (
    id SERIAL PRIMARY KEY,
    teacher_id INTEGER NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    is_booked BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (teacher_id, start_time, end_time)
);

CREATE TABLE IF NOT EXISTS registrations (
    id SERIAL PRIMARY KEY,
    slot_id INTEGER UNIQUE NOT NULL REFERENCES slots(id) ON DELETE CASCADE,
    teacher_id INTEGER NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,
    parent_name VARCHAR(100) NOT NULL,
    parent_email VARCHAR(150),
    parent_phone VARCHAR(50),
    child_name VARCHAR(100) NOT NULL,
    child_class VARCHAR(50) NOT NULL,
    note TEXT,
    status VARCHAR(30) DEFAULT 'active',
    cancel_reason TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        parent_email IS NOT NULL OR parent_phone IS NOT NULL
    )
);

CREATE TABLE IF NOT EXISTS parents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    child_name TEXT,
    child_class TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE parents ADD COLUMN IF NOT EXISTS child_name TEXT;
ALTER TABLE parents ADD COLUMN IF NOT EXISTS child_class TEXT;

CREATE TABLE IF NOT EXISTS auth_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    user_type TEXT NOT NULL,
    email TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS admin_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT,
    admin_email TEXT NOT NULL,
    action TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id TEXT,
    details JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS registration_settings (
    id BIGINT PRIMARY KEY DEFAULT 1,
    is_open BOOLEAN NOT NULL DEFAULT FALSE,
    opens_at TIMESTAMPTZ,
    closes_at TIMESTAMPTZ,
    updated_by BIGINT,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CHECK (id = 1),
    CHECK (opens_at IS NULL OR closes_at IS NULL OR opens_at < closes_at)
);

INSERT INTO registration_settings (id, is_open)
VALUES (1, FALSE)
ON CONFLICT (id) DO NOTHING;

INSERT INTO teachers (name, subject, room, email, password_hash)
VALUES (
  'Suraj Mirandu',
  'General',
  '101',
  'surajmirandu@gmail.com',
  '$2b$10$CyEX8Ga74nLT8QyP.0Kk..GuhUxAXMtj0OJukm2wtmqvUObCJp9ya'
)
ON CONFLICT (email) DO UPDATE SET
  name = EXCLUDED.name,
  subject = EXCLUDED.subject,
  room = EXCLUDED.room,
  password_hash = EXCLUDED.password_hash;

INSERT INTO admins (name, email, password_hash)
VALUES (
  'Site Admin',
  'admin@didzdvario.lt',
  '$2b$10$o8J17uL7i/k6DTfPJbTs1.G9z1ceWPdnRt2iXweiSTIpSv8pymmuW'
)
ON CONFLICT (email) DO UPDATE SET
  name = EXCLUDED.name,
  password_hash = EXCLUDED.password_hash;
