-- Supabase schema additions for authentication

CREATE TABLE IF NOT EXISTS parents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  child_name TEXT NOT NULL,
  child_class TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE parents ADD COLUMN IF NOT EXISTS child_name TEXT;
ALTER TABLE parents ADD COLUMN IF NOT EXISTS child_class TEXT;

CREATE TABLE IF NOT EXISTS auth_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  user_type TEXT NOT NULL,
  email TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS admin_audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id BIGINT,
  admin_email TEXT NOT NULL,
  action TEXT NOT NULL,
  target_type TEXT NOT NULL,
  target_id TEXT,
  details JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS registration_settings (
  id BIGINT PRIMARY KEY DEFAULT 1,
  is_open BOOLEAN NOT NULL DEFAULT FALSE,
  opens_at TIMESTAMPTZ,
  closes_at TIMESTAMPTZ,
  updated_by BIGINT,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CHECK (id = 1),
  CHECK (opens_at IS NULL OR closes_at IS NULL OR opens_at < closes_at)
);

INSERT INTO registration_settings (id, is_open)
VALUES (1, FALSE)
ON CONFLICT (id) DO NOTHING;
